# Generated by Django 3.1.6 on 2021-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_songs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='number',
            field=models.IntegerField(default=5, max_length=10),
            preserve_default=False,
        ),
    ]
