# Generated by Django 3.1.6 on 2021-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_songs_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='number',
            field=models.IntegerField(),
        ),
    ]
