# Generated by Django 3.1.6 on 2021-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210207_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='fullsong',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
