# Generated by Django 3.1.6 on 2021-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_songs_fullsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(default=1, verbose_name='lyrics'),
            preserve_default=False,
        ),
    ]
