# Generated by Django 3.1.6 on 2021-03-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_songs_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='slug',
            field=models.SlugField(null='true'),
            preserve_default='true',
        ),
    ]
