# Generated by Django 3.1.6 on 2021-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210306_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='slug',
            field=models.SlugField(null='false', unique=True),
        ),
    ]
